import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthProvider";
import  ButtonLogout  from "@/components/ButtonLogout";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] }, );

export const metadata: Metadata = {
  title: "hackathon_g2",
  description: "Generated by create next app",
};


const Header = () => {
  return (
    <header className="bg-gray-900  text-green-500 py-4">
      <div className="container mx-auto">
        <nav className="flex justify-between items-center">
          <div className="flex gap-5 items-center">
            <Link
              className="text-green-500 hover:text-green-800 transition-colors duration-300 cursor-pointer"
              href="/"
            >
              Página Inicial
            </Link>
          </div>
          <div>
            <ButtonLogout />
          </div>
        </nav>
      </div>
    </header>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 font-normal" >
        <AuthContextProvider>
          <Header />
          {children}
          </AuthContextProvider>
        </body>
    </html>
  );
}
